app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.home, name='home'),
    path('property-likes/', views.property_likes, name='video_likes'),
    path('update/', views.update, name='update'),
    path('test/', views.test, name='test')
]

app_rama/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/forms.py
from django import forms
from dashboard.models import RentType, Pets
from .models import Preference

BED_CHOICE = (
    ('0', 'ALL BEDS'),
    ('1', '1+ BEDS'),
    ('2', '2+ BEDS'),
    ('3', '3+ BEDS'),
)

BATH_CHOICE = (
    ('0', 'ALL BATHS'),
    ('1', '1+ BATHS'),
    ('2', '2+ BATHS'),
    ('3', '3+ BATHS'),
)

PET_CHOICE = (
    ('', 'Pets'),
    ('True', 'Pet Allowed'),
    ('False', 'No Pets'),
)


class PropertySearch(forms.Form):
    location = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control auto-complete', 'id': 'search_location', 'placeholder': 'Enter your location'}),
        required=False, )

    rent_type = forms.ModelChoiceField(queryset=RentType.objects.all(),
                                       required=False,
                                       empty_label=None,
                                       widget=forms.SelectMultiple(attrs={'class': 'form-control selectpicker',
                                                                          'data-style': "btn-selectpicker",
                                                                          'data-selected-text-format': "count &gt; 1",
                                                                          'title': 'All Rent Types'}))
    pet = forms.ChoiceField(choices=PET_CHOICE,
                            required=False,
                            widget=forms.Select(attrs={'class': 'form-control selectpicker',
                                                       'data-style': "btn-selectpicker"}))
    bed = forms.ChoiceField(choices=BED_CHOICE,
                            required=False,
                            widget=forms.Select(attrs={'class': 'form-control selectpicker ',
                                                       'data-style': "btn-selectpicker"}))

    bath = forms.ChoiceField(choices=BATH_CHOICE,
                             required=False,
                             widget=forms.Select(attrs={'class': 'form-control selectpicker mt-1',
                                                        'data-style': "btn-selectpicker"}))

    price_min = forms.CharField(widget=forms.HiddenInput(attrs={'id': 'id_price_min'}), required=False)
    price_max = forms.CharField(widget=forms.HiddenInput(attrs={'id': 'id_price_max', 'value': '30000'}),
                                required=False, )
    search_text = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control ', 'placeholder': 'Advanced Filter'}), required=False)
    near_check = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'custom-control-input'}),
                                    required=False)


class AutoComplete(forms.Form):
    autocomplete = forms.ModelChoiceField(queryset=Preference.objects.all(), empty_label=None,
                                          widget=forms.SelectMultiple())

app/templates/app/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

{% include 'app/basic/head.html' %}
<body style="padding-top: 72px;">

{% include 'app/basic/header.html' %}


<div class="container-fluid" >
    <div class="row">
        <div class="col-lg-6 py-4 p-xl-4">

            {% include 'app/basic/search_form.html' %}

            <hr class="mb-4 mt-1">
            <div class="ajax-container">
                <div class="d-flex justify-content-between align-items-center flex-column flex-md-row mb-4">
                    <div class="mr-3">
                        <p class="mb-3 mb-md-0"><strong id="all-counts">{{ properties_all|length }}</strong> results found</p>
                    </div>
                {#    <div>#}
                {#        <label class="form-label mr-2" for="form_sort">Sort by</label>#}
                {#        <select class="selectpicker" name="sort" id="form_sort" data-style="btn-selectpicker" title="">#}
                {#            <option value="sortBy_0">Most popular</option>#}
                {#            <option value="sortBy_1">Recommended</option>#}
                {#            <option value="sortBy_2">Newest</option>#}
                {#            <option value="sortBy_3">Oldest</option>#}
                {#            <option value="sortBy_4">Closest</option>#}
                {#        </select>#}
                {#    </div>#}
                </div>
                <div class="row infinite-container">
                    {% include 'app/basic/content.html' %}
                </div>
                <div id="more-container">
                    {% include 'app/basic/more_link.html' %}
                </div>

            </div>
        </div>

        <div class="col-lg-6 map-side-lg pr-lg-0">
            <div class="map-full shadow-left" id="categorySideMap" style="background-image: {% static 'img/bed.svg' %}"></div>
        </div>

        <input type="hidden" id="log" value="{{ request.user.is_authenticated }}">
    </div>
</div>


<!-- Script-->
{% include 'app/basic/home_script.html' %}
</body>
</html>

app/templates/app/test.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/multiple_autocomplete.css' %}">
</head>
<body>
    <div style="display:none;">
        {{ form.autocomplete }}
    </div>

    <div>
        <span class="autocomplete-select"></span>
    </div>
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bundle.min.js' %}"></script>
    <script>
    {# read data of selectbox and add data to autocomplete element#}
        var values2 = document.querySelectorAll('#id_autocomplete option');
        var values = [];
        for(let i = 0; i<values2.length; i++){
            values.push(
                {
                    label: values2[i].text,
                    value: values2[i].value,
                }
            )
        }

        var autocomplete = new SelectPure(".autocomplete-select", {
            options: values,
            value: [],
            multiple: true,
            autocomplete: true,
            icon: "fa fa-times",
            onChange: value => {
                {# update selectbox whenever autocomplete is changed #}
                console.log(value);
                $('#id_autocomplete').val(value);
            },
            classNames: {
                select: "select-pure__select",
                dropdownShown: "select-pure__select--opened",
                multiselect: "select-pure__select--multiple",
                label: "select-pure__label",
                placeholder: "select-pure__placeholder",
                dropdown: "select-pure__options",
                option: "select-pure__option",
                autocompleteInput: "select-pure__autocomplete",
                selectedLabel: "select-pure__selected-label",
                selectedOption: "select-pure__option--selected",
                placeholderHidden: "select-pure__placeholder--hidden",
                optionHidden: "select-pure__option--hidden",
            }
        });


    </script>
</body>
</html>